In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
claims = pd.read_csv('Medicare_Part_D_Spending_by_Drug_2022.csv')

In [4]:
claims.head()

,Brnd_Name,Gnrc_Name,Tot_Mftr,Mftr_Name,Tot_Spndng_2018,Tot_Dsg_Unts_2018,Tot_Clms_2018,Tot_Benes_2018,Avg_Spnd_Per_Dsg_Unt_Wghtd_2018,Avg_Spnd_Per_Clm_2018,...,Tot_Spndng_2022,Tot_Dsg_Unts_2022,Tot_Clms_2022,Tot_Benes_2022,Avg_Spnd_Per_Dsg_Unt_Wghtd_2022,Avg_Spnd_Per_Clm_2022,Avg_Spnd_Per_Bene_2022,Outlier_Flag_2022,Chg_Avg_Spnd_Per_Dsg_Unt_21_22,CAGR_Avg_Spnd_Per_Dsg_Unt_18_22
0,1st Tier Unifine Pentips,"Pen Needle, Diabetic",1,Overall,"$167,193.78","761,658","6,538","2,341",$0.22,$25.57,...,"$70,039.61","310,304","2,501","1,147",$0.23,$28.00,$61.06,0.0,0.01%,0.01%
1,1st Tier Unifine Pentips,"Pen Needle, Diabetic",1,Owen Mumford Us,"$167,193.78","761,658","6,538","2,341",$0.22,$25.57,...,"$70,039.61","310,304","2,501","1,147",$0.23,$28.00,$61.06,0.0,0.01%,0.01%
2,1st Tier Unifine Pentips Plus,"Pen Needle, Diabetic",1,Overall,"$369,402.85","1,813,908","14,931","5,674",$0.20,$24.74,...,"$114,601.54","486,206","3,846","1,474",$0.24,$29.80,$77.75,0.0,0.01%,0.04%
3,1st Tier Unifine Pentips Plus,"Pen Needle, Diabetic",1,Owen Mumford Us,"$369,402.85","1,813,908","14,931","5,674",$0.20,$24.74,...,"$114,601.54","486,206","3,846","1,474",$0.24,$29.80,$77.75,0.0,0.01%,0.04%
4,Abacavir,Abacavir Sulfate,6,Overall,"$10,653,423.32","3,034,767","40,388","7,359",$4.03,$263.78,...,"$6,945,563.71","2,035,106","24,317","3,452",$3.87,$285.63,"$2,012.04",0.0,0.21%,-0.01%

In [5]:
claims.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13889 entries, 0 to 13888
Data columns (total 46 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Brnd_Name                        13889 non-null  object
 1   Gnrc_Name                        13889 non-null  object
 2   Tot_Mftr                         13889 non-null  int64
 3   Mftr_Name                        13889 non-null  object
 4   Tot_Spndng_2018                  9647 non-null   object
 5   Tot_Dsg_Unts_2018                9647 non-null   object
 6   Tot_Clms_2018                    9647 non-null   object
 7   Tot_Benes_2018                   9573 non-null   object
 8   Avg_Spnd_Per_Dsg_Unt_Wghtd_2018  9647 non-null   object
 9   Avg_Spnd_Per_Clm_2018            9647 non-null   object
 10  Avg_Spnd_Per_Bene_2018           9478 non-null   object
 11  Outlier_Flag_2018                9645 non-null   float64
 12  Tot_Spndng_2019                  10706 non-null  object
 13  Tot_Dsg_Unts_2019                10706 non-null  object
 14  Tot_Clms_2019                    10706 non-null  object
 15  Tot_Benes_2019                   10533 non-null  object
 16  Avg_Spnd_Per_Dsg_Unt_Wghtd_2019  10706 non-null  object
 17  Avg_Spnd_Per_Clm_2019            10706 non-null  object
 18  Avg_Spnd_Per_Bene_2019           10477 non-null  object
 19  Outlier_Flag_2019                10703 non-null  float64
 20  Tot_Spndng_2020                  11715 non-null  object
 21  Tot_Dsg_Unts_2020                11715 non-null  object
 22  Tot_Clms_2020                    11715 non-null  object
 23  Tot_Benes_2020                   11465 non-null  object
 24  Avg_Spnd_Per_Dsg_Unt_Wghtd_2020  11715 non-null  object
 25  Avg_Spnd_Per_Clm_2020            11715 non-null  object
 26  Avg_Spnd_Per_Bene_2020           11433 non-null  object
 27  Outlier_Flag_2020                11710 non-null  float64
 28  Tot_Spndng_2021                  12724 non-null  object
 29  Tot_Dsg_Unts_2021                12724 non-null  object
 30  Tot_Clms_2021                    12724 non-null  object
 31  Tot_Benes_2021                   12323 non-null  object
 32  Avg_Spnd_Per_Dsg_Unt_Wghtd_2021  12724 non-null  object
 33  Avg_Spnd_Per_Clm_2021            12724 non-null  object
 34  Avg_Spnd_Per_Bene_2021           12319 non-null  object
 35  Outlier_Flag_2021                12718 non-null  float64
 36  Tot_Spndng_2022                  13889 non-null  object
 37  Tot_Dsg_Unts_2022                13889 non-null  object
 38  Tot_Clms_2022                    13889 non-null  object
 39  Tot_Benes_2022                   13189 non-null  object
 40  Avg_Spnd_Per_Dsg_Unt_Wghtd_2022  13889 non-null  object
 41  Avg_Spnd_Per_Clm_2022            13889 non-null  object
 42  Avg_Spnd_Per_Bene_2022           13189 non-null  object
 43  Outlier_Flag_2022                13876 non-null  float64
 44  Chg_Avg_Spnd_Per_Dsg_Unt_21_22   12724 non-null  object
 45  CAGR_Avg_Spnd_Per_Dsg_Unt_18_22  12841 non-null  object
dtypes: float64(5), int64(1), object(40)
memory usage: 4.9+ MB

In [12]:
claims.isnull().sum()

Brnd_Name                             0
Gnrc_Name                             0
Tot_Mftr                              0
Mftr_Name                             0
Tot_Spndng_2018                    4242
Tot_Dsg_Unts_2018                  4242
Tot_Clms_2018                      4242
Tot_Benes_2018                     4316
Avg_Spnd_Per_Dsg_Unt_Wghtd_2018    4242
Avg_Spnd_Per_Clm_2018              4242
Avg_Spnd_Per_Bene_2018             4411
Outlier_Flag_2018                  4244
Tot_Spndng_2019                    3183
Tot_Dsg_Unts_2019                  3183
Tot_Clms_2019                      3183
Tot_Benes_2019                     3356
Avg_Spnd_Per_Dsg_Unt_Wghtd_2019    3183
Avg_Spnd_Per_Clm_2019              3183
Avg_Spnd_Per_Bene_2019             3412
Outlier_Flag_2019                  3186
Tot_Spndng_2020                    2174
Tot_Dsg_Unts_2020                  2174
Tot_Clms_2020                      2174
Tot_Benes_2020                     2424
Avg_Spnd_Per_Dsg_Unt_Wghtd_2020    2174
Avg_Spnd_Per_Clm_2020              2174
Avg_Spnd_Per_Bene_2020             2456
Outlier_Flag_2020                  2179
Tot_Spndng_2021                    1165
Tot_Dsg_Unts_2021                  1165
Tot_Clms_2021                      1165
Tot_Benes_2021                     1566
Avg_Spnd_Per_Dsg_Unt_Wghtd_2021    1165
Avg_Spnd_Per_Clm_2021              1165
Avg_Spnd_Per_Bene_2021             1570
Outlier_Flag_2021                  1171
Tot_Spndng_2022                       0
Tot_Dsg_Unts_2022                     0
Tot_Clms_2022                         0
Tot_Benes_2022                      700
Avg_Spnd_Per_Dsg_Unt_Wghtd_2022       0
Avg_Spnd_Per_Clm_2022                 0
Avg_Spnd_Per_Bene_2022              700
Outlier_Flag_2022                    13
Chg_Avg_Spnd_Per_Dsg_Unt_21_22     1165
CAGR_Avg_Spnd_Per_Dsg_Unt_18_22    1048
dtype: int64

In [14]:
cols_to_keep = ["Brnd_Name", "Tot_Mftr", "Mftr_Name", "Tot_Spndng_2021", "Tot_Dsg_Unts_2021", "Tot_Clms_2021", "Tot_Benes_2021", "Avg_Spnd_Per_Dsg_Unt_Wghtd_2021", "Avg_Spnd_Per_Clm_2021", "Avg_Spnd_Per_Bene_2021", "Outlier_Flag_2021", "Tot_Spndng_2022", "Tot_Dsg_Unts_2022", "Tot_Clms_2022", "Tot_Benes_2022", "Avg_Spnd_Per_Dsg_Unt_Wghtd_2022", "Avg_Spnd_Per_Clm_2022", "Avg_Spnd_Per_Bene_2022", "Outlier_Flag_2022", "Chg_Avg_Spnd_Per_Dsg_Unt_21_22"]

updated_claims = claims[cols_to_keep]

In [16]:
updated_claims.head()

,Brnd_Name,Tot_Mftr,Mftr_Name,Tot_Spndng_2021,Tot_Dsg_Unts_2021,Tot_Clms_2021,Tot_Benes_2021,Avg_Spnd_Per_Dsg_Unt_Wghtd_2021,Avg_Spnd_Per_Clm_2021,Avg_Spnd_Per_Bene_2021,Outlier_Flag_2021,Tot_Spndng_2022,Tot_Dsg_Unts_2022,Tot_Clms_2022,Tot_Benes_2022,Avg_Spnd_Per_Dsg_Unt_Wghtd_2022,Avg_Spnd_Per_Clm_2022,Avg_Spnd_Per_Bene_2022,Outlier_Flag_2022,Chg_Avg_Spnd_Per_Dsg_Unt_21_22
0,1st Tier Unifine Pentips,1,Overall,"$102,280.76","459,384","3,708","1,313",$0.22,$27.58,$77.90,0.0,"$70,039.61","310,304","2,501","1,147",$0.23,$28.00,$61.06,0.0,0.01%
1,1st Tier Unifine Pentips,1,Owen Mumford Us,"$102,280.76","459,384","3,708","1,313",$0.22,$27.58,$77.90,0.0,"$70,039.61","310,304","2,501","1,147",$0.23,$28.00,$61.06,0.0,0.01%
2,1st Tier Unifine Pentips Plus,1,Overall,"$131,927.33","566,872","4,564","1,766",$0.23,$28.91,$74.70,0.0,"$114,601.54","486,206","3,846","1,474",$0.24,$29.80,$77.75,0.0,0.01%
3,1st Tier Unifine Pentips Plus,1,Owen Mumford Us,"$131,927.33","566,872","4,564","1,766",$0.23,$28.91,$74.70,0.0,"$114,601.54","486,206","3,846","1,474",$0.24,$29.80,$77.75,0.0,0.01%
4,Abacavir,6,Overall,"$7,036,063.99","2,500,817","30,527","4,254",$3.19,$230.49,"$1,653.99",0.0,"$6,945,563.71","2,035,106","24,317","3,452",$3.87,$285.63,"$2,012.04",0.0,0.21%

In [18]:
updated_claims.isnull().sum()

Brnd_Name                             0
Tot_Mftr                              0
Mftr_Name                             0
Tot_Spndng_2021                    1165
Tot_Dsg_Unts_2021                  1165
Tot_Clms_2021                      1165
Tot_Benes_2021                     1566
Avg_Spnd_Per_Dsg_Unt_Wghtd_2021    1165
Avg_Spnd_Per_Clm_2021              1165
Avg_Spnd_Per_Bene_2021             1570
Outlier_Flag_2021                  1171
Tot_Spndng_2022                       0
Tot_Dsg_Unts_2022                     0
Tot_Clms_2022                         0
Tot_Benes_2022                      700
Avg_Spnd_Per_Dsg_Unt_Wghtd_2022       0
Avg_Spnd_Per_Clm_2022                 0
Avg_Spnd_Per_Bene_2022              700
Outlier_Flag_2022                    13
Chg_Avg_Spnd_Per_Dsg_Unt_21_22     1165
dtype: int64

In [20]:
updated_claims_cop = updated_claims.copy()

In [40]:
clean_cop = updated_claims_cop.dropna()

In [41]:
clean_cop.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12138 entries, 0 to 13887
Data columns (total 20 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Brnd_Name                        12138 non-null  object
 1   Tot_Mftr                         12138 non-null  int64
 2   Mftr_Name                        12138 non-null  object
 3   Tot_Spndng_2021                  12138 non-null  object
 4   Tot_Dsg_Unts_2021                12138 non-null  object
 5   Tot_Clms_2021                    12138 non-null  object
 6   Tot_Benes_2021                   12138 non-null  object
 7   Avg_Spnd_Per_Dsg_Unt_Wghtd_2021  12138 non-null  object
 8   Avg_Spnd_Per_Clm_2021            12138 non-null  object
 9   Avg_Spnd_Per_Bene_2021           12138 non-null  object
 10  Outlier_Flag_2021                12138 non-null  float64
 11  Tot_Spndng_2022                  12138 non-null  object
 12  Tot_Dsg_Unts_2022                12138 non-null  object
 13  Tot_Clms_2022                    12138 non-null  object
 14  Tot_Benes_2022                   12138 non-null  object
 15  Avg_Spnd_Per_Dsg_Unt_Wghtd_2022  12138 non-null  object
 16  Avg_Spnd_Per_Clm_2022            12138 non-null  object
 17  Avg_Spnd_Per_Bene_2022           12138 non-null  object
 18  Outlier_Flag_2022                12138 non-null  float64
 19  Chg_Avg_Spnd_Per_Dsg_Unt_21_22   12138 non-null  object
dtypes: float64(2), int64(1), object(17)
memory usage: 1.9+ MB

In [42]:
clean_cop.describe(include='all')

,Brnd_Name,Tot_Mftr,Mftr_Name,Tot_Spndng_2021,Tot_Dsg_Unts_2021,Tot_Clms_2021,Tot_Benes_2021,Avg_Spnd_Per_Dsg_Unt_Wghtd_2021,Avg_Spnd_Per_Clm_2021,Avg_Spnd_Per_Bene_2021,Outlier_Flag_2021,Tot_Spndng_2022,Tot_Dsg_Unts_2022,Tot_Clms_2022,Tot_Benes_2022,Avg_Spnd_Per_Dsg_Unt_Wghtd_2022,Avg_Spnd_Per_Clm_2022,Avg_Spnd_Per_Bene_2022,Outlier_Flag_2022,Chg_Avg_Spnd_Per_Dsg_Unt_21_22
count,12138,12138.000000,12138,12138,12138,12138,12138,12138,12138,12138,12138.000000,12138,12138,12138,12138,12138,12138,12138,12138.000000,12138
unique,3122,NaN,835,9954,9764,7397,6271,2939,8304,9309,NaN,10013,9791,7302,6170,2969,8352,9296,NaN,286
top,Insulin Syringe,NaN,Overall,"$102,280.76",60,59,11,$0.22,$27.59,$47.95,NaN,"$70,039.61","1,900",51,13,$0.18,$10.33,$23.93,NaN,0.01%
freq,48,NaN,3227,2,7,25,50,107,6,5,NaN,2,6,25,60,102,7,5,NaN,797
mean,NaN,1.549514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.066980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.079090,NaN
std,NaN,2.482745,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.249997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.269891,NaN
min,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN
25%,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN
50%,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN
75%,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN
max,NaN,41.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN

In [43]:
numeric_cols = ["Tot_Spndng_2021", "Tot_Dsg_Unts_2021", "Tot_Clms_2021", "Tot_Benes_2021", "Avg_Spnd_Per_Dsg_Unt_Wghtd_2021", "Avg_Spnd_Per_Clm_2021", "Avg_Spnd_Per_Bene_2021", "Tot_Spndng_2022", "Tot_Dsg_Unts_2022", "Tot_Clms_2022", "Tot_Benes_2022", "Avg_Spnd_Per_Dsg_Unt_Wghtd_2022", "Avg_Spnd_Per_Clm_2022", "Avg_Spnd_Per_Bene_2022", "Chg_Avg_Spnd_Per_Dsg_Unt_21_22"]

# Convert columns to strings, remove "$" and "," signs, then convert back to numeric
for col in numeric_cols:
    clean_cop[col] = clean_cop[col].astype(str).str.replace("$", "").str.replace(",", "").str.replace("%", "")
    # Convert back to numeric after removing the special characters
    clean_cop[col] = pd.to_numeric(clean_cop[col], errors='coerce')

# Confirm changes
clean_cop.info()

C:\Users\obay\AppData\Local\Temp\ipykernel_27980\1378396410.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cop[col] = clean_cop[col].astype(str).str.replace("$", "").str.replace(",", "").str.replace("%", "")
C:\Users\obay\AppData\Local\Temp\ipykernel_27980\1378396410.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cop[col] = pd.to_numeric(clean_cop[col], errors='coerce')
C:\Users\obay\AppData\Local\Temp\ipykernel_27980\1378396410.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cop[col] = clean_cop[col].astype(str).str.replace("$", "").str.replace(",", "").str.replace("%", "")
C:\Users\obay\AppData\Local\Temp\ipykernel_27980\1378396410.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cop[col] = pd.to_numeric(clean_cop[col], errors='coerce')
C:\Users\obay\AppData\Local\Temp\ipykernel_27980\1378396410.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cop[col] = clean_cop[col].astype(str).str.replace("$", "").str.replace(",", "").str.replace("%", "")
C:\Users\obay\AppData\Local\Temp\ipykernel_27980\1378396410.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cop[col] = pd.to_numeric(clean_cop[col], errors='coerce')
C:\Users\obay\AppData\Local\Temp\ipykernel_27980\1378396410.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cop[col] = clean_cop[col].astype(str).str.replace("$", "").str.replace(",", "").str.replace("%", "")
C:\Users\obay\AppData\Local\Temp\ipykernel_27980\1378396410.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cop[col] = pd.to_numeric(clean_cop[col], errors='coerce')
C:\Users\obay\AppData\Local\Temp\ipykernel_27980\1378396410.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cop[col] = clean_cop[col].astype(str).str.replace("$", "").str.replace(",", "").str.replace("%", "")
C:\Users\obay\AppData\Local\Temp\ipykernel_27980\1378396410.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cop[col] = pd.to_numeric(clean_cop[col], errors='coerce')
C:\Users\obay\AppData\Local\Temp\ipykernel_27980\1378396410.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cop[col] = clean_cop[col].astype(str).str.replace("$", "").str.replace(",", "").str.replace("%", "")
C:\Users\obay\AppData\Local\Temp\ipykernel_27980\1378396410.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cop[col] = pd.to_numeric(clean_cop[col], errors='coerce')
C:\Users\obay\AppData\Local\Temp\ipykernel_27980\1378396410.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cop[col] = clean_cop[col].astype(str).str.replace("$", "").str.replace(",", "").str.replace("%", "")
C:\Users\obay\AppData\Local\Temp\ipykernel_27980\1378396410.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cop[col] = pd.to_numeric(clean_cop[col], errors='coerce')
C:\Users\obay\AppData\Local\Temp\ipykernel_27980\1378396410.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cop[col] = clean_cop[col].astype(str).str.replace("$", "").str.replace(",", "").str.replace("%", "")
C:\Users\obay\AppData\Local\Temp\ipykernel_27980\1378396410.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cop[col] = pd.to_numeric(clean_cop[col], errors='coerce')

<class 'pandas.core.frame.DataFrame'>
Index: 12138 entries, 0 to 13887
Data columns (total 20 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Brnd_Name                        12138 non-null  object
 1   Tot_Mftr                         12138 non-null  int64
 2   Mftr_Name                        12138 non-null  object
 3   Tot_Spndng_2021                  12138 non-null  float64
 4   Tot_Dsg_Unts_2021                12138 non-null  int64
 5   Tot_Clms_2021                    12138 non-null  int64
 6   Tot_Benes_2021                   12138 non-null  int64
 7   Avg_Spnd_Per_Dsg_Unt_Wghtd_2021  12138 non-null  float64
 8   Avg_Spnd_Per_Clm_2021            12138 non-null  float64
 9   Avg_Spnd_Per_Bene_2021           12138 non-null  float64
 10  Outlier_Flag_2021                12138 non-null  float64
 11  Tot_Spndng_2022                  12138 non-null  float64
 12  Tot_Dsg_Unts_2022                12138 non-null  int64
 13  Tot_Clms_2022                    12138 non-null  int64
 14  Tot_Benes_2022                   12138 non-null  int64
 15  Avg_Spnd_Per_Dsg_Unt_Wghtd_2022  12138 non-null  float64
 16  Avg_Spnd_Per_Clm_2022            12138 non-null  float64
 17  Avg_Spnd_Per_Bene_2022           12138 non-null  float64
 18  Outlier_Flag_2022                12138 non-null  float64
 19  Chg_Avg_Spnd_Per_Dsg_Unt_21_22   12138 non-null  float64
dtypes: float64(11), int64(7), object(2)
memory usage: 1.9+ MB

C:\Users\obay\AppData\Local\Temp\ipykernel_27980\1378396410.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cop[col] = clean_cop[col].astype(str).str.replace("$", "").str.replace(",", "").str.replace("%", "")
C:\Users\obay\AppData\Local\Temp\ipykernel_27980\1378396410.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cop[col] = pd.to_numeric(clean_cop[col], errors='coerce')
C:\Users\obay\AppData\Local\Temp\ipykernel_27980\1378396410.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cop[col] = clean_cop[col].astype(str).str.replace("$", "").str.replace(",", "").str.replace("%", "")
C:\Users\obay\AppData\Local\Temp\ipykernel_27980\1378396410.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cop[col] = pd.to_numeric(clean_cop[col], errors='coerce')
C:\Users\obay\AppData\Local\Temp\ipykernel_27980\1378396410.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cop[col] = clean_cop[col].astype(str).str.replace("$", "").str.replace(",", "").str.replace("%", "")
C:\Users\obay\AppData\Local\Temp\ipykernel_27980\1378396410.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cop[col] = pd.to_numeric(clean_cop[col], errors='coerce')
C:\Users\obay\AppData\Local\Temp\ipykernel_27980\1378396410.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cop[col] = clean_cop[col].astype(str).str.replace("$", "").str.replace(",", "").str.replace("%", "")
C:\Users\obay\AppData\Local\Temp\ipykernel_27980\1378396410.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cop[col] = pd.to_numeric(clean_cop[col], errors='coerce')
C:\Users\obay\AppData\Local\Temp\ipykernel_27980\1378396410.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cop[col] = clean_cop[col].astype(str).str.replace("$", "").str.replace(",", "").str.replace("%", "")
C:\Users\obay\AppData\Local\Temp\ipykernel_27980\1378396410.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cop[col] = pd.to_numeric(clean_cop[col], errors='coerce')
C:\Users\obay\AppData\Local\Temp\ipykernel_27980\1378396410.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cop[col] = clean_cop[col].astype(str).str.replace("$", "").str.replace(",", "").str.replace("%", "")
C:\Users\obay\AppData\Local\Temp\ipykernel_27980\1378396410.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cop[col] = pd.to_numeric(clean_cop[col], errors='coerce')
C:\Users\obay\AppData\Local\Temp\ipykernel_27980\1378396410.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cop[col] = clean_cop[col].astype(str).str.replace("$", "").str.replace(",", "").str.replace("%", "")
C:\Users\obay\AppData\Local\Temp\ipykernel_27980\1378396410.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cop[col] = pd.to_numeric(clean_cop[col], errors='coerce')

In [44]:
clean_cop.head()

,Brnd_Name,Tot_Mftr,Mftr_Name,Tot_Spndng_2021,Tot_Dsg_Unts_2021,Tot_Clms_2021,Tot_Benes_2021,Avg_Spnd_Per_Dsg_Unt_Wghtd_2021,Avg_Spnd_Per_Clm_2021,Avg_Spnd_Per_Bene_2021,Outlier_Flag_2021,Tot_Spndng_2022,Tot_Dsg_Unts_2022,Tot_Clms_2022,Tot_Benes_2022,Avg_Spnd_Per_Dsg_Unt_Wghtd_2022,Avg_Spnd_Per_Clm_2022,Avg_Spnd_Per_Bene_2022,Outlier_Flag_2022,Chg_Avg_Spnd_Per_Dsg_Unt_21_22
0,1st Tier Unifine Pentips,1,Overall,102280.76,459384,3708,1313,0.22,27.58,77.90,0.0,70039.61,310304,2501,1147,0.23,28.00,61.06,0.0,0.01
1,1st Tier Unifine Pentips,1,Owen Mumford Us,102280.76,459384,3708,1313,0.22,27.58,77.90,0.0,70039.61,310304,2501,1147,0.23,28.00,61.06,0.0,0.01
2,1st Tier Unifine Pentips Plus,1,Overall,131927.33,566872,4564,1766,0.23,28.91,74.70,0.0,114601.54,486206,3846,1474,0.24,29.80,77.75,0.0,0.01
3,1st Tier Unifine Pentips Plus,1,Owen Mumford Us,131927.33,566872,4564,1766,0.23,28.91,74.70,0.0,114601.54,486206,3846,1474,0.24,29.80,77.75,0.0,0.01
4,Abacavir,6,Overall,7036063.99,2500817,30527,4254,3.19,230.49,1653.99,0.0,6945563.71,2035106,24317,3452,3.87,285.63,2012.04,0.0,0.21

In [45]:
clean_cop.describe()

,Tot_Mftr,Tot_Spndng_2021,Tot_Dsg_Unts_2021,Tot_Clms_2021,Tot_Benes_2021,Avg_Spnd_Per_Dsg_Unt_Wghtd_2021,Avg_Spnd_Per_Clm_2021,Avg_Spnd_Per_Bene_2021,Outlier_Flag_2021,Tot_Spndng_2022,Tot_Dsg_Unts_2022,Tot_Clms_2022,Tot_Benes_2022,Avg_Spnd_Per_Dsg_Unt_Wghtd_2022,Avg_Spnd_Per_Clm_2022,Avg_Spnd_Per_Bene_2022,Outlier_Flag_2022,Chg_Avg_Spnd_Per_Dsg_Unt_21_22
count,12138.000000,1.213800e+04,1.213800e+04,1.213800e+04,1.213800e+04,12138.000000,12138.000000,1.213800e+04,12138.000000,1.213800e+04,1.213800e+04,1.213800e+04,1.213800e+04,12138.000000,12138.000000,1.213800e+04,12138.000000,12138.000000
mean,1.549514,3.551203e+07,1.884119e+07,2.470175e+05,7.698817e+04,190.920095,1572.923992,8.984462e+03,0.066980,3.919114e+07,1.962271e+07,2.532777e+05,8.039729e+04,195.456005,1622.443240,9.570478e+03,0.079090,0.066600
std,2.482745,2.593197e+08,1.196132e+08,1.455054e+06,3.909469e+05,1582.590838,6466.797008,5.116854e+04,0.249997,3.069641e+08,1.272146e+08,1.501978e+06,4.124327e+05,1581.385036,6728.162442,5.290896e+04,0.269891,0.925169
min,1.000000,4.350000e+01,1.100000e+01,1.100000e+01,1.100000e+01,0.000000,0.040000,1.000000e-01,0.000000,3.306000e+01,9.000000e+00,1.200000e+01,1.100000e+01,0.000000,1.090000,2.090000e+00,0.000000,-0.960000
25%,1.000000,9.394920e+04,2.626200e+04,5.622500e+02,2.020000e+02,0.490000,31.280000,7.783500e+01,0.000000,7.848785e+04,2.255000e+04,5.040000e+02,1.740000e+02,0.490000,30.730000,7.734250e+01,0.000000,-0.040000
50%,1.000000,1.153475e+06,2.593270e+05,4.901500e+03,1.604000e+03,2.090000,110.415000,2.868400e+02,0.000000,1.101339e+06,2.406370e+05,4.695500e+03,1.546000e+03,2.120000,108.780000,2.802650e+02,0.000000,0.020000
75%,1.000000,8.398421e+06,2.928171e+06,4.917825e+04,1.649900e+04,13.980000,573.167500,1.819375e+03,0.000000,8.457658e+06,2.848457e+06,5.004525e+04,1.634900e+04,14.027500,570.240000,1.840178e+03,0.000000,0.070000
max,41.000000,1.257515e+10,4.338696e+09,6.109988e+07,1.495589e+07,42825.010000,195601.830000,1.561519e+06,1.000000,1.521981e+10,4.654341e+09,6.479730e+07,1.588574e+07,39993.790000,193748.050000,1.595176e+06,1.000000,64.750000

In [47]:
print(clean_cop["Outlier_Flag_2021"].value_counts())
print("\n")
print(clean_cop["Outlier_Flag_2022"].value_counts())

Outlier_Flag_2021
0.0    11325
1.0      813
Name: count, dtype: int64


Outlier_Flag_2022
0.0    11178
1.0      960
Name: count, dtype: int64

In [48]:
claim_2021_cols = ["Brnd_Name", "Tot_Mftr", "Mftr_Name", "Tot_Spndng_2021", "Tot_Dsg_Unts_2021", "Tot_Clms_2021", "Tot_Benes_2021", "Avg_Spnd_Per_Dsg_Unt_Wghtd_2021", "Avg_Spnd_Per_Clm_2021", "Avg_Spnd_Per_Bene_2021", "Outlier_Flag_2021"]

claim_2022_cols = ["Brnd_Name", "Tot_Mftr", "Mftr_Name", "Tot_Spndng_2022", "Tot_Dsg_Unts_2022", "Tot_Clms_2022", "Tot_Benes_2022", "Avg_Spnd_Per_Dsg_Unt_Wghtd_2022", "Avg_Spnd_Per_Clm_2022", "Avg_Spnd_Per_Bene_2022", "Outlier_Flag_2022"]

claims_2021 = clean_cop[claim_2021_cols]
claims_2022 = clean_cop[claim_2022_cols]

In [52]:
display(claims_2021.describe())
print("\n")
print("\n")
display(claims_2022.describe())

,Tot_Mftr,Tot_Spndng_2021,Tot_Dsg_Unts_2021,Tot_Clms_2021,Tot_Benes_2021,Avg_Spnd_Per_Dsg_Unt_Wghtd_2021,Avg_Spnd_Per_Clm_2021,Avg_Spnd_Per_Bene_2021,Outlier_Flag_2021
count,12138.000000,1.213800e+04,1.213800e+04,1.213800e+04,1.213800e+04,12138.000000,12138.000000,1.213800e+04,12138.000000
mean,1.549514,3.551203e+07,1.884119e+07,2.470175e+05,7.698817e+04,190.920095,1572.923992,8.984462e+03,0.066980
std,2.482745,2.593197e+08,1.196132e+08,1.455054e+06,3.909469e+05,1582.590838,6466.797008,5.116854e+04,0.249997
min,1.000000,4.350000e+01,1.100000e+01,1.100000e+01,1.100000e+01,0.000000,0.040000,1.000000e-01,0.000000
25%,1.000000,9.394920e+04,2.626200e+04,5.622500e+02,2.020000e+02,0.490000,31.280000,7.783500e+01,0.000000
50%,1.000000,1.153475e+06,2.593270e+05,4.901500e+03,1.604000e+03,2.090000,110.415000,2.868400e+02,0.000000
75%,1.000000,8.398421e+06,2.928171e+06,4.917825e+04,1.649900e+04,13.980000,573.167500,1.819375e+03,0.000000
max,41.000000,1.257515e+10,4.338696e+09,6.109988e+07,1.495589e+07,42825.010000,195601.830000,1.561519e+06,1.000000

,Tot_Mftr,Tot_Spndng_2022,Tot_Dsg_Unts_2022,Tot_Clms_2022,Tot_Benes_2022,Avg_Spnd_Per_Dsg_Unt_Wghtd_2022,Avg_Spnd_Per_Clm_2022,Avg_Spnd_Per_Bene_2022,Outlier_Flag_2022
count,12138.000000,1.213800e+04,1.213800e+04,1.213800e+04,1.213800e+04,12138.000000,12138.000000,1.213800e+04,12138.000000
mean,1.549514,3.919114e+07,1.962271e+07,2.532777e+05,8.039729e+04,195.456005,1622.443240,9.570478e+03,0.079090
std,2.482745,3.069641e+08,1.272146e+08,1.501978e+06,4.124327e+05,1581.385036,6728.162442,5.290896e+04,0.269891
min,1.000000,3.306000e+01,9.000000e+00,1.200000e+01,1.100000e+01,0.000000,1.090000,2.090000e+00,0.000000
25%,1.000000,7.848785e+04,2.255000e+04,5.040000e+02,1.740000e+02,0.490000,30.730000,7.734250e+01,0.000000
50%,1.000000,1.101339e+06,2.406370e+05,4.695500e+03,1.546000e+03,2.120000,108.780000,2.802650e+02,0.000000
75%,1.000000,8.457658e+06,2.848457e+06,5.004525e+04,1.634900e+04,14.027500,570.240000,1.840178e+03,0.000000
max,41.000000,1.521981e+10,4.654341e+09,6.479730e+07,1.588574e+07,39993.790000,193748.050000,1.595176e+06,1.000000